#!/usr/bin/env bash
# ============================================================================
# Leave-one-source-out cross-validation for 1j (MynaNet)
# ============================================================================
# Addresses Reviewer-2 concern #7: the manuscript reports a single MIP
# 80:10:10 split with no domain-shift or source-disjoint evaluation.  A LOSO
# protocol groups by Xeno-canto source_id (xc<N>) and ensures that for each
# fold, the training set contains zero clips from the test fold's source
# recordings.
#
# Protocol:
#   * K = 5 folds.  Folds are built by partitioning sources into 5 strata
#     such that each species is approximately balanced across folds.
#   * For each fold: train on 4 folds' sources, test on the held-out fold.
#   * Per fold, train 1j with the canonical CLI (n_mels=64, dropout=0.05,
#     warmup=70, mixup=0.2) — single seed (42) to keep wall time tractable.
#   * Total: 5 runs × ~52 min/seed ≈ 4.5 h on Linux/CUDA.
#
# Idempotency: each fold is skipped if the expected result directory exists.
#
# Usage:
#   bash run_loso_cv.sh                       # all 5 folds
#   bash run_loso_cv.sh 0                     # only fold 0
#   bash run_loso_cv.sh 0 2 4                 # specific folds
#
# Requires:
#   * splits CSVs generated by build_loso_splits.py (one CSV per fold)
#   * 1j_mbv3_se.py in develop/
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
META_DIR="/Volumes/Evo/MYGARDENBIRD/metadata16khz"
FLAT_DIR="/Volumes/Evo/MYGARDENBIRD/mygardenbird16khz"
SCRIPT_1J="$SCRIPT_DIR/develop/1j_mbv3_se.py"
LOSO_BUILDER="$SCRIPT_DIR/build_loso_splits.py"
RESULTS_ROOT="$SCRIPT_DIR/results_mygardenbird_1_$(python3 -c 'import platform; print(platform.system().lower())')"
CONDA_ENV="${CONDA_ENV:-tf215_gpu}"
SEED=42
K=5

# Canonical args identical to 1j's main protocol.
COMMON_ARGS=(
    --flat_dir       "$FLAT_DIR"
    --n_mels         64
    --dropout        0.05
    --warmup_epochs  70
    --mixup          0.2
)

# Step 1: build LOSO split CSVs if missing.
if ! ls "$META_DIR"/splits_loso_k${K}_fold*.csv >/dev/null 2>&1; then
    echo ""
    echo "▶▶▶ Building LOSO splits (K=$K)"
    if [[ ! -f "$LOSO_BUILDER" ]]; then
        echo "✗ MISSING $LOSO_BUILDER — write it before running" >&2
        exit 1
    fi
    conda run -n "$CONDA_ENV" python3 "$LOSO_BUILDER" \
        --clips_csv "$META_DIR/clips.csv" \
        --output_dir "$META_DIR" \
        --k "$K"
fi

run_fold() {
    local fold="$1"
    local csv="$META_DIR/splits_loso_k${K}_fold${fold}.csv"
    local result_dir="$RESULTS_ROOT/1j_mbv3_se_mels64_drop05_rand${SEED}_warm70_mixup0.2_loso_k${K}_fold${fold}_$(python3 -c 'import platform; print(platform.system().lower())')"

    if [[ -f "$result_dir/model_int8.tflite" ]]; then
        echo "  ↷ SKIP fold $fold (already complete)"
        return 0
    fi
    if [[ ! -f "$csv" ]]; then
        echo "  ✗ MISSING $csv" >&2; return 1
    fi
    if [[ ! -f "$SCRIPT_1J" ]]; then
        echo "  ✗ MISSING $SCRIPT_1J" >&2; return 1
    fi

    echo ""
    echo "════════════════════════════════════════════════════"
    echo "  1j LOSO fold $fold / $((K-1))"
    echo "════════════════════════════════════════════════════"

    conda run -n "$CONDA_ENV" python3 "$SCRIPT_1J" \
        --splits_csv  "$csv" \
        "${COMMON_ARGS[@]}" \
        --random_seed "$SEED"
}

FOLDS=()
for a in "$@"; do
    case "$a" in
        0|1|2|3|4) FOLDS+=("$a") ;;
        *) echo "Unknown fold: $a (expected 0-4)" >&2; exit 2 ;;
    esac
done
if [[ ${#FOLDS[@]} -eq 0 ]]; then
    FOLDS=(0 1 2 3 4)
fi

mkdir -p "$RESULTS_ROOT"

for fold in "${FOLDS[@]}"; do
    run_fold "$fold" || true
done

echo ""
echo "════════════════════════════════════════════════════"
echo "  LOSO CV complete."
echo "  Results: $RESULTS_ROOT"
echo "  Aggregate with: python3 analyze_loso_results.py"
echo "════════════════════════════════════════════════════"
